

import { useState, useCallback } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import styles from './AiSummary.module.css'

export default function AiSummary({ summary }) {
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [revealed, setRevealed] = useState(false)

  if (!summary) return null

  const handleClick = useCallback(() => {
    if (open) {
      setOpen(false)
      return
    }

    setOpen(true)
    setLoading(true)
    setRevealed(false)

    setTimeout(() => {
      setLoading(false)
      setRevealed(true)
    }, 1800)
  }, [open])

  return (
    <div className={styles.wrapper}>
      <button
        className={`${styles.trigger} ${open ? styles.triggerOpen : ''}`}
        onClick={handleClick}
        aria-expanded={open}
        disabled={loading}
      >
        <span className={styles.triggerLeft}>
          <svg className={`${styles.sparkle} ${loading ? styles.sparkleAnim : ''}`} width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
            <path d="M12 0L14.59 8.41L23 11L14.59 13.59L12 22L9.41 13.59L1 11L9.41 8.41L12 0Z" />
          </svg>
          <span className={styles.triggerLabel}>
            {loading ? 'Generating summary...' : 'Summarize with AI'}
          </span>
        </span>
        {!loading && (
          <svg
            className={`${styles.chevron} ${open ? styles.chevronOpen : ''}`}
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <polyline points="6 9 12 15 18 9" />
          </svg>
        )}
      </button>

      <AnimatePresence>
        {open && (
          <motion.div
            className={styles.panel}
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
          >
            <div className={styles.panelInner}>
              {loading ? (
                <div className={styles.skeleton}>
                  <div className={styles.skeletonLine} style={{ width: '100%' }} />
                  <div className={styles.skeletonLine} style={{ width: '92%' }} />
                  <div className={styles.skeletonLine} style={{ width: '97%' }} />
                  <div className={styles.skeletonLine} style={{ width: '60%' }} />
                </div>
              ) : revealed ? (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.4 }}
                >
                  <span className={styles.panelLabel}>AI Summary</span>
                  <p className={styles.panelText}>{summary}</p>
                  <p className={styles.disclaimer}>Generated by AI. May contain inaccuracies.</p>
                </motion.div>
              ) : null}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
