import { defineConfig } from 'astro/config'
import react from '@astrojs/react'

export default defineConfig({
  // Used for absolute URLs; the whole-site sitemap is generated by
  // scripts/generate-sitemap.mjs, not the Astro sitemap integration.
  site: 'https://www.oussamabettaieb.com',
  base: '/blog',
  integrations: [react()],
  vite: {
    css: {
      modules: {
        localsConvention: 'camelCase',
      },
    },
  },
})
